const { contextBridge, ipcRenderer } = require('electron')

// sandbox: true 时 preload 不能加载本地 CommonJS 模块，因此通道名在此处保持为
// 最小只读映射；主进程仍以 src/shared/ipc-channels.js 为唯一注册来源。
const CHANNELS = Object.freeze({
  APP_INFO: 'app:info',
  APP_CONFIRM: 'app:confirm',
  APP_BROWSE_FILE: 'app:browseFile',
  PORTS_LIST: 'ports:list',
  PORTS_FIND: 'ports:find',
  PORTS_KILL_PORT: 'ports:killPort',
  PORTS_KILL_PID: 'ports:killPid',
  SYSTEM_INFO: 'system:info',
  QUICKLAUNCH_GET: 'quicklaunch:get',
  QUICKLAUNCH_SAVE: 'quicklaunch:save',
  QUICKLAUNCH_LAUNCH: 'quicklaunch:launch',
  QUICKLAUNCH_LAUNCH_URLS: 'quicklaunch:launchUrls',
  QUICKLAUNCH_IMPORT_URLS: 'quicklaunch:importUrls',
  QUICKLAUNCH_PARSE_URLS: 'quicklaunch:parseUrls',
  QUICKLAUNCH_EXPORT_URLS: 'quicklaunch:exportUrls',
  CLIPBOARD_GET_HISTORY: 'clipboard:getHistory',
  CLIPBOARD_SAVE_HISTORY: 'clipboard:saveHistory',
  CLIPBOARD_READ: 'clipboard:read',
  CLIPBOARD_WRITE: 'clipboard:write',
  SFTP_CONFIG_GET: 'sftp:getConfig',
  SFTP_CONFIG_SAVE: 'sftp:saveConfig',
  SFTP_PATHS_GET: 'sftp:getPaths',
  SFTP_PATHS_SAVE: 'sftp:savePaths',
  SFTP_TEST: 'sftp:test',
  SFTP_LIST: 'sftp:list',
  SFTP_UPLOAD: 'sftp:upload',
  SFTP_DEPLOY_ZIP: 'sftp:deployZip',
  SFTP_DELETE: 'sftp:delete',
  SFTP_COMPARE: 'sftp:compare',
  SFTP_LOCAL_LIST: 'sftp:localList',
  SFTP_MKDIR: 'sftp:mkdir',
  SFTP_PREFLIGHT: 'sftp:preflight',
  SFTP_PROFILES_GET: 'sftp:getProfiles',
  SFTP_PROFILE_SAVE: 'sftp:saveProfile',
  SFTP_PROFILE_ACTIVATE: 'sftp:activateProfile',
  SFTP_PROFILE_DELETE: 'sftp:deleteProfile',
  SFTP_HISTORY_GET: 'sftp:getHistory',
  SFTP_ROLLBACK: 'sftp:rollback',
  GPT_IMAGE_CONFIG_GET: 'gptImage:getConfig',
  GPT_IMAGE_CONFIG_SAVE: 'gptImage:saveConfig',
  GPT_IMAGE_MODELS_LIST: 'gptImage:listModels',
  GPT_IMAGE_GENERATE: 'gptImage:generate',
  GPT_IMAGE_SAVE: 'gptImage:save',
  GPT_IMAGE_HISTORY_GET: 'gptImage:getHistory',
  GPT_IMAGE_HISTORY_SAVE: 'gptImage:saveHistory',
  GPT_IMAGE_HISTORY_CLEAR: 'gptImage:clearHistory',
  MODEL_TEST_LIST_PROVIDERS: 'modelTest:listProviders',
  MODEL_TEST_RUN: 'modelTest:run',
  MODEL_TEST_CANCEL: 'modelTest:cancel',
  MODEL_TEST_LIST_MODELS: 'modelTest:listModels',
  MODEL_TEST_MODEL_LIST_SETTINGS_GET: 'modelTest:getModelListSettings',
  MODEL_TEST_MODEL_LIST_SETTINGS_SAVE: 'modelTest:saveModelListSettings',
  MODEL_TEST_COPY_PROVIDER_VALUE: 'modelTest:copyProviderValue',
  MODEL_TEST_HISTORY_GET: 'modelTest:getHistory',
  MODEL_TEST_HISTORY_SAVE: 'modelTest:saveHistory',
  MODEL_TEST_MONITOR_GET: 'modelTest:getMonitorSettings',
  MODEL_TEST_MONITOR_SAVE: 'modelTest:saveMonitorSettings',
  MODEL_TEST_MONITOR_RUN: 'modelTest:runInspection',
  OPS_DASHBOARD_GET: 'ops:getDashboard',
})

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args)

contextBridge.exposeInMainWorld('opsApi', Object.freeze({
  getAppInfo: () => invoke(CHANNELS.APP_INFO),
  listPorts: () => invoke(CHANNELS.PORTS_LIST),
  findPort: port => invoke(CHANNELS.PORTS_FIND, port),
  killPort: (port, signal = 'SIGTERM') => invoke(CHANNELS.PORTS_KILL_PORT, { port, signal }),
  killPid: (pid, signal = 'SIGTERM') => invoke(CHANNELS.PORTS_KILL_PID, { pid, signal }),
  confirm: options => invoke(CHANNELS.APP_CONFIRM, options),
  getSystemInfo: () => invoke(CHANNELS.SYSTEM_INFO),
  getQuickLaunchItems: () => invoke(CHANNELS.QUICKLAUNCH_GET),
  saveQuickLaunchItems: items => invoke(CHANNELS.QUICKLAUNCH_SAVE, items),
  launchItem: item => invoke(CHANNELS.QUICKLAUNCH_LAUNCH, item),
  launchQuickLaunchUrls: items => invoke(CHANNELS.QUICKLAUNCH_LAUNCH_URLS, items),
  importQuickLaunchUrls: () => invoke(CHANNELS.QUICKLAUNCH_IMPORT_URLS),
  parseQuickLaunchUrls: raw => invoke(CHANNELS.QUICKLAUNCH_PARSE_URLS, raw),
  exportQuickLaunchUrls: items => invoke(CHANNELS.QUICKLAUNCH_EXPORT_URLS, items),
  browseFile: options => invoke(CHANNELS.APP_BROWSE_FILE, options),
  getClipboardHistory: () => invoke(CHANNELS.CLIPBOARD_GET_HISTORY),
  saveClipboardHistory: history => invoke(CHANNELS.CLIPBOARD_SAVE_HISTORY, history),
  readClipboard: () => invoke(CHANNELS.CLIPBOARD_READ),
  writeClipboard: content => invoke(CHANNELS.CLIPBOARD_WRITE, content),
  getSftpConfig: () => invoke(CHANNELS.SFTP_CONFIG_GET),
  saveSftpConfig: config => invoke(CHANNELS.SFTP_CONFIG_SAVE, config),
  getSftpPaths: () => invoke(CHANNELS.SFTP_PATHS_GET),
  saveSftpPaths: paths => invoke(CHANNELS.SFTP_PATHS_SAVE, paths),
  sftpTest: () => invoke(CHANNELS.SFTP_TEST),
  sftpList: dirPath => invoke(CHANNELS.SFTP_LIST, dirPath),
  sftpUpload: (localPath, remotePath) => invoke(CHANNELS.SFTP_UPLOAD, { localPath, remotePath }),
  sftpDeployZip: payload => invoke(CHANNELS.SFTP_DEPLOY_ZIP, payload),
  sftpDelete: remotePath => invoke(CHANNELS.SFTP_DELETE, remotePath),
  sftpCompare: (localDir, remoteDir) => invoke(CHANNELS.SFTP_COMPARE, { localDir, remoteDir }),
  sftpLocalList: localDir => invoke(CHANNELS.SFTP_LOCAL_LIST, localDir),
  sftpMkdir: remotePath => invoke(CHANNELS.SFTP_MKDIR, remotePath),
  sftpPreflight: payload => invoke(CHANNELS.SFTP_PREFLIGHT, payload),
  getSftpProfiles: () => invoke(CHANNELS.SFTP_PROFILES_GET),
  saveSftpProfile: profile => invoke(CHANNELS.SFTP_PROFILE_SAVE, profile),
  activateSftpProfile: profileId => invoke(CHANNELS.SFTP_PROFILE_ACTIVATE, profileId),
  deleteSftpProfile: profileId => invoke(CHANNELS.SFTP_PROFILE_DELETE, profileId),
  getSftpHistory: () => invoke(CHANNELS.SFTP_HISTORY_GET),
  rollbackSftpRelease: releaseId => invoke(CHANNELS.SFTP_ROLLBACK, releaseId),
  getGptImageConfig: () => invoke(CHANNELS.GPT_IMAGE_CONFIG_GET),
  saveGptImageConfig: config => invoke(CHANNELS.GPT_IMAGE_CONFIG_SAVE, config),
  listGptImageModels: config => invoke(CHANNELS.GPT_IMAGE_MODELS_LIST, config),
  generateGptImage: payload => invoke(CHANNELS.GPT_IMAGE_GENERATE, payload),
  saveGptImage: payload => invoke(CHANNELS.GPT_IMAGE_SAVE, payload),
  getGptImageHistory: () => invoke(CHANNELS.GPT_IMAGE_HISTORY_GET),
  saveGptImageHistory: history => invoke(CHANNELS.GPT_IMAGE_HISTORY_SAVE, history),
  clearGptImageHistory: () => invoke(CHANNELS.GPT_IMAGE_HISTORY_CLEAR),
  listModelProviders: () => invoke(CHANNELS.MODEL_TEST_LIST_PROVIDERS),
  listProviderModels: payload => invoke(CHANNELS.MODEL_TEST_LIST_MODELS, payload),
  getModelListSettings: () => invoke(CHANNELS.MODEL_TEST_MODEL_LIST_SETTINGS_GET),
  saveModelListSettings: settings => invoke(CHANNELS.MODEL_TEST_MODEL_LIST_SETTINGS_SAVE, settings),
  copyModelProviderValue: payload => invoke(CHANNELS.MODEL_TEST_COPY_PROVIDER_VALUE, payload),
  runModelTest: payload => invoke(CHANNELS.MODEL_TEST_RUN, payload),
  cancelModelTestRun: runId => invoke(CHANNELS.MODEL_TEST_CANCEL, runId),
  getModelTestHistory: () => invoke(CHANNELS.MODEL_TEST_HISTORY_GET),
  saveModelTestHistory: snapshot => invoke(CHANNELS.MODEL_TEST_HISTORY_SAVE, snapshot),
  getModelMonitorSettings: () => invoke(CHANNELS.MODEL_TEST_MONITOR_GET),
  saveModelMonitorSettings: settings => invoke(CHANNELS.MODEL_TEST_MONITOR_SAVE, settings),
  runModelInspection: () => invoke(CHANNELS.MODEL_TEST_MONITOR_RUN),
  getOpsDashboard: () => invoke(CHANNELS.OPS_DASHBOARD_GET),
}))
