const { contextBridge, ipcRenderer } = require('electron')

// sandbox: true 时 preload 不能加载本地 CommonJS 模块，因此通道名在此处保持为
// 最小只读映射；主进程仍以 src/shared/ipc-channels.js 为唯一注册来源。
const CHANNELS = Object.freeze({
  APP_INFO: 'app:info',
  APP_CONFIRM: 'app:confirm',
  APP_BROWSE_FILE: 'app:browseFile',
  APP_RELAUNCH: 'app:relaunch',
  DATA_BACKUP_OVERVIEW: 'dataBackup:getOverview',
  DATA_BACKUP_EXPORT: 'dataBackup:export',
  DATA_BACKUP_INSPECT: 'dataBackup:inspect',
  DATA_BACKUP_RESTORE: 'dataBackup:restore',
  DATA_BACKUP_AUTO_GET: 'dataBackup:getAutoSettings',
  DATA_BACKUP_AUTO_SAVE: 'dataBackup:saveAutoSettings',
  DATA_BACKUP_AUTO_RUN: 'dataBackup:runAutoBackup',
  DATA_BACKUP_HISTORY_GET: 'dataBackup:getAutoHistory',
  DATA_BACKUP_AUTO_HEALTH_GET: 'dataBackup:getAutoHealth',
  DATA_BACKUP_AUTO_INSPECT: 'dataBackup:inspectAutoBackup',
  DATA_BACKUP_AUTO_RESTORE: 'dataBackup:restoreAutoBackup',
  DATA_BACKUP_AUTO_DELETE: 'dataBackup:deleteAutoBackup',
  DATA_BACKUP_AUTO_OPEN_DIRECTORY: 'dataBackup:openAutoBackupDirectory',
  DATA_BACKUP_RESTORE_POINTS_GET: 'dataBackup:getRestorePoints',
  DATA_BACKUP_RESTORE_POINT: 'dataBackup:restorePoint',
  PORTS_LIST: 'ports:list',
  PORTS_FIND: 'ports:find',
  PORTS_KILL_PORT: 'ports:killPort',
  PORTS_KILL_PID: 'ports:killPid',
  NODE_MONITOR_GET: 'nodeMonitor:get',
  NODE_MONITOR_WATCH: 'nodeMonitor:watch',
  NODE_MONITOR_UNWATCH: 'nodeMonitor:unwatch',
  NODE_MONITOR_CHECK: 'nodeMonitor:check',
  SYSTEM_INFO: 'system:info',
  QUICKLAUNCH_GET: 'quicklaunch:get',
  QUICKLAUNCH_SAVE: 'quicklaunch:save',
  QUICKLAUNCH_LAUNCH: 'quicklaunch:launch',
  QUICKLAUNCH_LAUNCH_URLS: 'quicklaunch:launchUrls',
  QUICKLAUNCH_IMPORT_URLS: 'quicklaunch:importUrls',
  QUICKLAUNCH_PARSE_URLS: 'quicklaunch:parseUrls',
  QUICKLAUNCH_EXPORT_URLS: 'quicklaunch:exportUrls',
  CLIPBOARD_GET_HISTORY: 'clipboard:getHistory',
  CLIPBOARD_SAVE_HISTORY: 'clipboard:saveHistory',
  CLIPBOARD_READ: 'clipboard:read',
  CLIPBOARD_WRITE: 'clipboard:write',
  SFTP_CONFIG_GET: 'sftp:getConfig',
  SFTP_CONFIG_SAVE: 'sftp:saveConfig',
  SFTP_PATHS_GET: 'sftp:getPaths',
  SFTP_PATHS_SAVE: 'sftp:savePaths',
  SFTP_TEST: 'sftp:test',
  SFTP_LIST: 'sftp:list',
  SFTP_UPLOAD: 'sftp:upload',
  SFTP_DEPLOY_ZIP: 'sftp:deployZip',
  SFTP_DELETE: 'sftp:delete',
  SFTP_COMPARE: 'sftp:compare',
  SFTP_LOCAL_LIST: 'sftp:localList',
  SFTP_MKDIR: 'sftp:mkdir',
  SFTP_PREFLIGHT: 'sftp:preflight',
  SFTP_PROFILES_GET: 'sftp:getProfiles',
  SFTP_PROFILE_SAVE: 'sftp:saveProfile',
  SFTP_PROFILE_ACTIVATE: 'sftp:activateProfile',
  SFTP_PROFILE_DELETE: 'sftp:deleteProfile',
  SFTP_HISTORY_GET: 'sftp:getHistory',
  SFTP_ROLLBACK: 'sftp:rollback',
  GPT_IMAGE_CONFIG_GET: 'gptImage:getConfig',
  GPT_IMAGE_CONFIG_SAVE: 'gptImage:saveConfig',
  GPT_IMAGE_MODELS_LIST: 'gptImage:listModels',
  GPT_IMAGE_GENERATE: 'gptImage:generate',
  GPT_IMAGE_SAVE: 'gptImage:save',
  GPT_IMAGE_HISTORY_GET: 'gptImage:getHistory',
  GPT_IMAGE_HISTORY_SAVE: 'gptImage:saveHistory',
  GPT_IMAGE_HISTORY_CLEAR: 'gptImage:clearHistory',
  MODEL_TEST_LIST_PROVIDERS: 'modelTest:listProviders',
  MODEL_TEST_RUN: 'modelTest:run',
  MODEL_TEST_CANCEL: 'modelTest:cancel',
  MODEL_TEST_LIST_MODELS: 'modelTest:listModels',
  MODEL_TEST_MODEL_LIST_SETTINGS_GET: 'modelTest:getModelListSettings',
  MODEL_TEST_MODEL_LIST_SETTINGS_SAVE: 'modelTest:saveModelListSettings',
  MODEL_TEST_COPY_PROVIDER_VALUE: 'modelTest:copyProviderValue',
  MODEL_TEST_HISTORY_GET: 'modelTest:getHistory',
  MODEL_TEST_HISTORY_SAVE: 'modelTest:saveHistory',
  MODEL_TEST_MONITOR_GET: 'modelTest:getMonitorSettings',
  MODEL_TEST_MONITOR_SAVE: 'modelTest:saveMonitorSettings',
  MODEL_TEST_MONITOR_RUN: 'modelTest:runInspection',
  OPS_DASHBOARD_GET: 'ops:getDashboard',
  AI_OPS_GET_STATE: 'aiOps:getState',
  AI_PROVIDER_SOURCE_LIST: 'aiOps:listProviderSources',
  AI_PROVIDER_SOURCE_ADD: 'aiOps:addProviderFromModelReliability',
  AI_PROVIDER_DELETE: 'aiOps:deleteProvider',
  AI_PROVIDER_ACTIVATE: 'aiOps:activateProvider',
  AI_PROVIDER_TEST: 'aiOps:testProvider',
  AI_CHAT_ASK: 'aiOps:askChat',
  AI_EVALUATION_SAVE_CASES: 'aiOps:saveEvaluationCases',
  AI_EVALUATION_RUN: 'aiOps:runEvaluation',
  AI_LOG_ANALYZE: 'aiOps:analyzeLog',
  AI_KNOWLEDGE_SAVE: 'aiOps:saveKnowledge',
  AI_KNOWLEDGE_DELETE: 'aiOps:deleteKnowledge',
  AI_KNOWLEDGE_SEARCH: 'aiOps:searchKnowledge',
  AI_KNOWLEDGE_ANSWER: 'aiOps:answerKnowledge',
  AI_WORKFLOW_PLAN: 'aiOps:planWorkflow',
  AI_WORKFLOW_EXECUTE: 'aiOps:executeWorkflow',
  AI_COPILOT_ASK: 'aiOps:askCopilot',
  AI_KNOWLEDGE_IMPORT: 'aiOps:importKnowledge',
  OPS_EVENTS_GET: 'ops:getEvents',
  OPS_EVENT_UPDATE: 'ops:updateEvent',
  OPS_EVENTS_MARK_READ: 'ops:markEventsRead',
  OPS_NOTIFICATION_PREFERENCES_GET: 'ops:getNotificationPreferences',
  OPS_NOTIFICATION_PREFERENCES_SAVE: 'ops:saveNotificationPreferences',
  OPS_NOTIFICATION_TEST: 'ops:testNotification',
  OPS_NOTIFICATION_OPEN: 'ops:openNotification',
  OPS_AUTOMATION_GET: 'ops:getAutomationTasks',
  OPS_AUTOMATION_SAVE: 'ops:saveAutomationTask',
  OPS_AUTOMATION_DELETE: 'ops:deleteAutomationTask',
  OPS_AUTOMATION_RUN: 'ops:runAutomationTask',
  AI_MCP_INFO: 'aiOps:getMcpInfo',
})

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args)
const subscribe = (channel, listener) => {
  if (typeof listener !== 'function') return () => {}
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on(channel, handler)
  return () => ipcRenderer.removeListener(channel, handler)
}

contextBridge.exposeInMainWorld('opsApi', Object.freeze({
  getAppInfo: () => invoke(CHANNELS.APP_INFO),
  listPorts: () => invoke(CHANNELS.PORTS_LIST),
  findPort: port => invoke(CHANNELS.PORTS_FIND, port),
  killPort: (port, signal = 'SIGTERM') => invoke(CHANNELS.PORTS_KILL_PORT, { port, signal }),
  killPid: (pid, signal = 'SIGTERM') => invoke(CHANNELS.PORTS_KILL_PID, { pid, signal }),
  getNodeServiceWatches: () => invoke(CHANNELS.NODE_MONITOR_GET),
  watchNodeService: service => invoke(CHANNELS.NODE_MONITOR_WATCH, service),
  unwatchNodeService: service => invoke(CHANNELS.NODE_MONITOR_UNWATCH, service),
  checkNodeServiceWatches: () => invoke(CHANNELS.NODE_MONITOR_CHECK),
  confirm: options => invoke(CHANNELS.APP_CONFIRM, options),
  relaunchApp: () => invoke(CHANNELS.APP_RELAUNCH),
  getDataBackupOverview: () => invoke(CHANNELS.DATA_BACKUP_OVERVIEW),
  exportDataBackup: options => invoke(CHANNELS.DATA_BACKUP_EXPORT, options),
  inspectDataBackup: options => invoke(CHANNELS.DATA_BACKUP_INSPECT, options),
  restoreDataBackup: options => invoke(CHANNELS.DATA_BACKUP_RESTORE, options),
  getAutoBackupSettings: () => invoke(CHANNELS.DATA_BACKUP_AUTO_GET),
  saveAutoBackupSettings: options => invoke(CHANNELS.DATA_BACKUP_AUTO_SAVE, options),
  runAutoBackupNow: () => invoke(CHANNELS.DATA_BACKUP_AUTO_RUN),
  getAutoBackupHistory: () => invoke(CHANNELS.DATA_BACKUP_HISTORY_GET),
  getAutoBackupHealth: () => invoke(CHANNELS.DATA_BACKUP_AUTO_HEALTH_GET),
  inspectAutoBackup: id => invoke(CHANNELS.DATA_BACKUP_AUTO_INSPECT, { id }),
  restoreAutoBackup: id => invoke(CHANNELS.DATA_BACKUP_AUTO_RESTORE, { id }),
  deleteAutoBackup: id => invoke(CHANNELS.DATA_BACKUP_AUTO_DELETE, { id }),
  openAutoBackupDirectory: id => invoke(CHANNELS.DATA_BACKUP_AUTO_OPEN_DIRECTORY, { id }),
  getDataRestorePoints: () => invoke(CHANNELS.DATA_BACKUP_RESTORE_POINTS_GET),
  restoreDataRestorePoint: id => invoke(CHANNELS.DATA_BACKUP_RESTORE_POINT, { id }),
  getSystemInfo: () => invoke(CHANNELS.SYSTEM_INFO),
  getQuickLaunchItems: () => invoke(CHANNELS.QUICKLAUNCH_GET),
  saveQuickLaunchItems: items => invoke(CHANNELS.QUICKLAUNCH_SAVE, items),
  launchItem: item => invoke(CHANNELS.QUICKLAUNCH_LAUNCH, item),
  launchQuickLaunchUrls: items => invoke(CHANNELS.QUICKLAUNCH_LAUNCH_URLS, items),
  importQuickLaunchUrls: () => invoke(CHANNELS.QUICKLAUNCH_IMPORT_URLS),
  parseQuickLaunchUrls: raw => invoke(CHANNELS.QUICKLAUNCH_PARSE_URLS, raw),
  exportQuickLaunchUrls: items => invoke(CHANNELS.QUICKLAUNCH_EXPORT_URLS, items),
  browseFile: options => invoke(CHANNELS.APP_BROWSE_FILE, options),
  getClipboardHistory: () => invoke(CHANNELS.CLIPBOARD_GET_HISTORY),
  saveClipboardHistory: history => invoke(CHANNELS.CLIPBOARD_SAVE_HISTORY, history),
  readClipboard: () => invoke(CHANNELS.CLIPBOARD_READ),
  writeClipboard: content => invoke(CHANNELS.CLIPBOARD_WRITE, content),
  getSftpConfig: () => invoke(CHANNELS.SFTP_CONFIG_GET),
  saveSftpConfig: config => invoke(CHANNELS.SFTP_CONFIG_SAVE, config),
  getSftpPaths: () => invoke(CHANNELS.SFTP_PATHS_GET),
  saveSftpPaths: paths => invoke(CHANNELS.SFTP_PATHS_SAVE, paths),
  sftpTest: () => invoke(CHANNELS.SFTP_TEST),
  sftpList: dirPath => invoke(CHANNELS.SFTP_LIST, dirPath),
  sftpUpload: (localPath, remotePath) => invoke(CHANNELS.SFTP_UPLOAD, { localPath, remotePath }),
  sftpDeployZip: payload => invoke(CHANNELS.SFTP_DEPLOY_ZIP, payload),
  sftpDelete: remotePath => invoke(CHANNELS.SFTP_DELETE, remotePath),
  sftpCompare: (localDir, remoteDir) => invoke(CHANNELS.SFTP_COMPARE, { localDir, remoteDir }),
  sftpLocalList: localDir => invoke(CHANNELS.SFTP_LOCAL_LIST, localDir),
  sftpMkdir: remotePath => invoke(CHANNELS.SFTP_MKDIR, remotePath),
  sftpPreflight: payload => invoke(CHANNELS.SFTP_PREFLIGHT, payload),
  getSftpProfiles: () => invoke(CHANNELS.SFTP_PROFILES_GET),
  saveSftpProfile: profile => invoke(CHANNELS.SFTP_PROFILE_SAVE, profile),
  activateSftpProfile: profileId => invoke(CHANNELS.SFTP_PROFILE_ACTIVATE, profileId),
  deleteSftpProfile: profileId => invoke(CHANNELS.SFTP_PROFILE_DELETE, profileId),
  getSftpHistory: () => invoke(CHANNELS.SFTP_HISTORY_GET),
  rollbackSftpRelease: releaseId => invoke(CHANNELS.SFTP_ROLLBACK, releaseId),
  getGptImageConfig: () => invoke(CHANNELS.GPT_IMAGE_CONFIG_GET),
  saveGptImageConfig: config => invoke(CHANNELS.GPT_IMAGE_CONFIG_SAVE, config),
  listGptImageModels: config => invoke(CHANNELS.GPT_IMAGE_MODELS_LIST, config),
  generateGptImage: payload => invoke(CHANNELS.GPT_IMAGE_GENERATE, payload),
  saveGptImage: payload => invoke(CHANNELS.GPT_IMAGE_SAVE, payload),
  getGptImageHistory: () => invoke(CHANNELS.GPT_IMAGE_HISTORY_GET),
  saveGptImageHistory: history => invoke(CHANNELS.GPT_IMAGE_HISTORY_SAVE, history),
  clearGptImageHistory: () => invoke(CHANNELS.GPT_IMAGE_HISTORY_CLEAR),
  listModelProviders: () => invoke(CHANNELS.MODEL_TEST_LIST_PROVIDERS),
  listProviderModels: payload => invoke(CHANNELS.MODEL_TEST_LIST_MODELS, payload),
  getModelListSettings: () => invoke(CHANNELS.MODEL_TEST_MODEL_LIST_SETTINGS_GET),
  saveModelListSettings: settings => invoke(CHANNELS.MODEL_TEST_MODEL_LIST_SETTINGS_SAVE, settings),
  copyModelProviderValue: payload => invoke(CHANNELS.MODEL_TEST_COPY_PROVIDER_VALUE, payload),
  runModelTest: payload => invoke(CHANNELS.MODEL_TEST_RUN, payload),
  cancelModelTestRun: runId => invoke(CHANNELS.MODEL_TEST_CANCEL, runId),
  getModelTestHistory: () => invoke(CHANNELS.MODEL_TEST_HISTORY_GET),
  saveModelTestHistory: snapshot => invoke(CHANNELS.MODEL_TEST_HISTORY_SAVE, snapshot),
  getModelMonitorSettings: () => invoke(CHANNELS.MODEL_TEST_MONITOR_GET),
  saveModelMonitorSettings: settings => invoke(CHANNELS.MODEL_TEST_MONITOR_SAVE, settings),
  runModelInspection: () => invoke(CHANNELS.MODEL_TEST_MONITOR_RUN),
  getOpsDashboard: () => invoke(CHANNELS.OPS_DASHBOARD_GET),
  getAiOpsState: () => invoke(CHANNELS.AI_OPS_GET_STATE),
  listAiProviderSources: () => invoke(CHANNELS.AI_PROVIDER_SOURCE_LIST),
  addAiProviderFromModelReliability: input => invoke(CHANNELS.AI_PROVIDER_SOURCE_ADD, input),
  deleteAiProvider: id => invoke(CHANNELS.AI_PROVIDER_DELETE, id),
  activateAiProvider: id => invoke(CHANNELS.AI_PROVIDER_ACTIVATE, id),
  testAiProvider: id => invoke(CHANNELS.AI_PROVIDER_TEST, id),
  askAiChat: options => invoke(CHANNELS.AI_CHAT_ASK, options),
  saveAiEvaluationCases: cases => invoke(CHANNELS.AI_EVALUATION_SAVE_CASES, cases),
  runAiEvaluation: options => invoke(CHANNELS.AI_EVALUATION_RUN, options),
  analyzeAiLog: options => invoke(CHANNELS.AI_LOG_ANALYZE, options),
  saveAiKnowledge: document => invoke(CHANNELS.AI_KNOWLEDGE_SAVE, document),
  deleteAiKnowledge: id => invoke(CHANNELS.AI_KNOWLEDGE_DELETE, id),
  searchAiKnowledge: query => invoke(CHANNELS.AI_KNOWLEDGE_SEARCH, query),
  answerAiKnowledge: options => invoke(CHANNELS.AI_KNOWLEDGE_ANSWER, options),
  planAiWorkflow: prompt => invoke(CHANNELS.AI_WORKFLOW_PLAN, prompt),
  executeAiWorkflow: options => invoke(CHANNELS.AI_WORKFLOW_EXECUTE, options),
  askAiCopilot: options => invoke(CHANNELS.AI_COPILOT_ASK, options),
  importAiKnowledge: filePath => invoke(CHANNELS.AI_KNOWLEDGE_IMPORT, filePath),
  getOpsEvents: options => invoke(CHANNELS.OPS_EVENTS_GET, options),
  updateOpsEvent: (id, status) => invoke(CHANNELS.OPS_EVENT_UPDATE, { id, status }),
  markOpsEventsRead: options => invoke(CHANNELS.OPS_EVENTS_MARK_READ, options),
  getOpsNotificationPreferences: () => invoke(CHANNELS.OPS_NOTIFICATION_PREFERENCES_GET),
  saveOpsNotificationPreferences: preferences => invoke(CHANNELS.OPS_NOTIFICATION_PREFERENCES_SAVE, preferences),
  testOpsNotification: () => invoke(CHANNELS.OPS_NOTIFICATION_TEST),
  onOpsNotificationOpen: listener => subscribe(CHANNELS.OPS_NOTIFICATION_OPEN, listener),
  getAutomationTasks: () => invoke(CHANNELS.OPS_AUTOMATION_GET),
  saveAutomationTask: task => invoke(CHANNELS.OPS_AUTOMATION_SAVE, task),
  deleteAutomationTask: id => invoke(CHANNELS.OPS_AUTOMATION_DELETE, id),
  runAutomationTask: id => invoke(CHANNELS.OPS_AUTOMATION_RUN, id),
  getAiMcpInfo: () => invoke(CHANNELS.AI_MCP_INFO),
}))
